### ISSUE TITLE
Добавление обработчика входящих команд от бота

### ISSUE THREAD

**Issue by Pacman29** [TeamDevIU/Bot#10]

**Comment by reijo1337** [comment]
Создание комнаты. POST запрос. Передается название комнаты в теле, информация о юзере-источнике заявки. Что-то типа
`{
    roomName: 'This is room name',
    ownerInfo: {}
}`

**Comment by reijo1337** [comment]
Получение списка комнат. GET запрос на `/rooms/{role}`. В зависимости от роли вернется разный список комнат.
reader - список всех комнат в которых участвует юзер
moderator - список комнат в которые юзер может писать
admin - список комнат которе юзер может админить (удалять, добавлять редакторов и т.п.)
